experiment:
    name: ResNet34 Pretrained
    agent: Tester

dirs:
    base_dir: experiments/

settings:
    seed: 1337
    verbose: False
    print_metrics: True
    
    cuda: True
    gpu_device: 0
    
    mixedprec: False
    distributed: False
    async_loading: True

model:
    name: AutoSpeechResNet34
    
    checkpoint_dir: ""
    checkpoint_file: ""
    initial_model: pretrained_weights/ResNet34.pth
    summary_dir: ""

    num_classes: 1251
    init_channels: 128

test:
    dataset: VoxCeleb1
    file_list: data/test_list.txt
    base_path: data/voxceleb1/test/wav/
    nDataLoaderThread: 1
    print_interval: 100

    preprocessing_function: autospeech_preprocessing
    sampling_rate: 16000
    window_length: 25
    window_step: 10
    n_fft: 512
    partial_n_frames: 300
    audio_norm_target_dBFS: -30
    mean_file: data/voxceleb1/mean.npy
    std_file: data/voxceleb1/std.npy