experiment:
    name: ResNetSE34L Pretrained
    agent:

dirs:
    base_dir: experiments/

settings:
    seed: 1337
    verbose: False
    print_metrics: False
    
    cuda: True
    gpu_device: 0
    
    mixedprec: False
    distributed: False
    async_loading: True

model:
    name: ResNetSE34L
    
    checkpoint_dir: ""
    checkpoint_file: ""
    initial_model: pretrained_weights/ResNetSE34L.model
    summary_dir: ""

    layers: [3, 4, 6, 3]
    num_filters: [16, 32, 64, 128]
    encoder_type: SAP
    n_mels: 40
    nOut: 512
    log_input: True

test:
    dataset: VoxCeleb1
    file_list: data/test_list.txt
    base_path: data/voxceleb1/test/wav/
    nDataLoaderThread: 1
    print_interval: 100

    preprocessing_function: voxceleb_trainer_preprocessing
    sampling_rate: 16000
    max_frames: 400
    num_eval: 10