experiment:
    name: SincNet Pretrained
    agent:

dirs:
    base_dir: experiments/

settings:
    seed: 1337
    verbose: False
    print_metrics: False
    
    cuda: True
    gpu_device: 0
    
    mixedprec: False
    distributed: False
    async_loading: True

model:
    name: SincNet
    
    checkpoint_dir: ""
    checkpoint_file: ""
    initial_model: pretrained_weights/SincNet.pth
    summary_dir: ""

    fs: 16000
    cw_len: 200
    cw_shift: 10

test:
    dataset: VoxCeleb1
    file_list: data/test_list.txt
    base_path: data/voxceleb1/test/wav/
    nDataLoaderThread: 1
    print_interval: 100

    preprocessing_function: amplitude_preprocessing
    sampling_rate: 16000